# Site settings
title: "Marc Osterland's Resume"
description: "A little bit about Marc and his Past."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Marc Osterland"
resume_title:                   "Data Science & Bioinformatics Researcher"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "marc.osterland@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+491716497689"
resume_contact_address:         "Berlin, Germany"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Hi! I am a Bioinformatician with a deep passion for solving data-centered problems.
I have worked as research assistant and just finished my PhD (thesis submitted, defense soon) at the Zuse Institute Berlin & Freie Universität Berlin.
During this time I have worked mainly in interdisciplinary collaboration projects in an agile environment.</p>
<p>Since 2013 I am working with large data-sets and data-driven methods such as Machine Learning.
I have hands-on experience in training supervised and unsupervised models, ranging from Random Forests
to Deep Neural Networks. This experience comes from various research projects based on medical imaging
and multi-dimensional time-series data.</p>
<p>Historically, I may have a small bias towards biological and medical applications.
But I am looking forward to work in a new field that fascinates me, like mobility,
renewable energies, space exploration, robotics, and many more.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/marcosterland"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/marcosterland"
  resume_instagram_url:         "https://www.instagram.com/marcosterland/"
  resume_website_url:           "http://marcosterland.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
